//==================================================================================================
/// @file  test_softbody.cpp
/// @brief  Validation of soft body simulation (PBD cloth, volume, collision).
//==================================================================================================
#include "include/ciphyxs/CiPhyxs.hpp"
#include <cstdio>
#include <cmath>
#include <cstdlib>

// ── Helper ──────────────────────────────────────────────────────────────────────────────────────
bool approx(float a, float b, float eps = 1e-3f) { return std::abs(a - b) < eps; }

int main() {
    using namespace ciphyxs;
    int failures = 0;
    int tests    = 0;

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 1. Soft body creation — cloth factory
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;
        auto cloth = SoftBody::createCloth(5, 5, 0.5f, 1.0f);

        // 5×5 grid → 25 particles
        if (cloth.particleCount() != 25) {
            printf("FAIL 1a: Expected 25 particles, got %zu\n", cloth.particleCount());
            ++failures;
        }

        // Structural constraints: (5-1)*5 + (5-1)*5 = 40 horizontal+vertical
        // + shear: (5-1)*(5-1)*2 = 32 diagonal
        // + cross-edge bend: (5-1)*(5-1)*2 = 32
        // Total = 104 distance constraints
        std::size_t expectedDist = static_cast<std::size_t>(
            (5-1)*5 + (5-1)*5 + (5-1)*(5-1)*2 + (5-1)*(5-1)*2);
        if (cloth.distanceConstraints.size() != expectedDist) {
            printf("FAIL 1b: Expected %zu distance constraints, got %zu\n",
                   expectedDist, cloth.distanceConstraints.size());
            ++failures;
        }

        // Bend constraints are not generated by default (cross-edge model uses distance).
        if (!cloth.bendConstraints.empty()) {
            printf("FAIL 1c: Expected 0 bend constraints, got %zu\n",
                   cloth.bendConstraints.size());
            ++failures;
        }

        // All particles should have the same inverse mass.
        float invMass = cloth.inverseMasses[0];
        bool allSame = true;
        for (std::size_t i = 1; i < cloth.particleCount(); ++i) {
            if (std::abs(cloth.inverseMasses[i] - invMass) > 1e-6f) {
                allSame = false;
                break;
            }
        }
        if (!allSame) {
            printf("FAIL 1d: Not all particles have same inverse mass\n");
            ++failures;
        }

        printf("PASS 1: Cloth factory (%zu particles, %zu constraints)\n",
               cloth.particleCount(), cloth.distanceConstraints.size());
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 2. Soft body creation — volume factory
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;
        auto volume = SoftBody::createVolume(Vec3f(0.0f, 1.0f, 0.0f), 2.0f, 1.0f);

        // 8 particles
        if (volume.particleCount() != 8) {
            printf("FAIL 2a: Expected 8 particles, got %zu\n", volume.particleCount());
            ++failures;
        }

        // 12 edges
        if (volume.distanceConstraints.size() != 12) {
            printf("FAIL 2b: Expected 12 distance constraints, got %zu\n",
                   volume.distanceConstraints.size());
            ++failures;
        }

        // 5 volume constraints (tetrahedra)
        if (volume.volumeConstraints.size() != 5) {
            printf("FAIL 2c: Expected 5 volume constraints, got %zu\n",
                   volume.volumeConstraints.size());
            ++failures;
        }

        printf("PASS 2: Volume factory (%zu particles, %zu vol constraints)\n",
               volume.particleCount(), volume.volumeConstraints.size());
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 3. Soft body creation — rope factory
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;
        auto rope = SoftBody::createRope(Vec3f::zero(), Vec3f(5.0f, 0.0f, 0.0f), 5, 1.0f);

        // 5 segments → 6 particles
        if (rope.particleCount() != 6) {
            printf("FAIL 3a: Expected 6 particles, got %zu\n", rope.particleCount());
            ++failures;
        }

        // 5 distance constraints
        if (rope.distanceConstraints.size() != 5) {
            printf("FAIL 3b: Expected 5 distance constraints, got %zu\n",
                   rope.distanceConstraints.size());
            ++failures;
        }

        // First particle at start, last at end
        if (!approx(rope.positions[0].x, 0.0f) || !approx(rope.positions[5].x, 5.0f)) {
            printf("FAIL 3c: Rope endpoints wrong: (%.2f, %.2f)\n",
                   rope.positions[0].x, rope.positions[5].x);
            ++failures;
        }

        printf("PASS 3: Rope factory (%zu particles, %zu constraints)\n",
               rope.particleCount(), rope.distanceConstraints.size());
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 4. Soft body pin/unpin
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;
        auto cloth = SoftBody::createCloth(3, 3, 1.0f, 1.0f);

        // Pin corners.
        cloth.pinParticle(0);  // (0,0)
        cloth.pinParticle(2);  // (2,0)
        cloth.pinParticle(6);  // (0,2)
        cloth.pinParticle(8);  // (2,2)

        if (cloth.inverseMasses[0] != 0.0f || cloth.pinned[0] != 1) {
            printf("FAIL 4a: Pin failed for particle 0\n");
            ++failures;
        }
        if (cloth.inverseMasses[8] != 0.0f || cloth.pinned[8] != 1) {
            printf("FAIL 4b: Pin failed for particle 8\n");
            ++failures;
        }

        // Unpin particle 0.
        cloth.unpinParticle(0, 1.0f);
        if (cloth.inverseMasses[0] <= 0.0f || cloth.pinned[0] != 0) {
            printf("FAIL 4c: Unpin failed for particle 0\n");
            ++failures;
        }

        printf("PASS 4: Pin/unpin API\n");
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 5. Cloth gravity simulation (basic PBD integration test)
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;
        PhysicsWorld world;

        // Create a small cloth pinned at two corners.
        auto cloth = SoftBody::createCloth(4, 4, 1.0f, 1.0f);
        cloth.pinParticle(0);   // (0,0)
        cloth.pinParticle(3);   // (3,0)
        cloth.constraintIterations = 8;
        cloth.damping = 0.1f;
        world.addSoftBody(std::move(cloth));

        // Simulate for 2 seconds.
        for (int i = 0; i < 120; ++i) {
            world.step(1.0f / 60.0f);
        }

        // Unpinned particles should have fallen downward (negative Y).
        auto& sb = world.softBodies()[0];
        bool anyFell = false;
        for (std::size_t i = 0; i < sb.particleCount(); ++i) {
            if (!sb.pinned[i] && sb.positions[i].y < -0.5f) {
                anyFell = true;
                break;
            }
        }

        if (!anyFell) {
            printf("FAIL 5a: No unpinned particles fell downward.\n");
            printf("  Particle positions:\n");
            for (std::size_t i = 0; i < sb.particleCount(); ++i) {
                printf("    [%zu] pinned=%d pos=(%.3f, %.3f, %.3f)\n",
                       i, sb.pinned[i], sb.positions[i].x, sb.positions[i].y, sb.positions[i].z);
            }
            ++failures;
        }

        // Pinned particles should still be at roughly y=0.
        if (std::abs(sb.positions[0].y) > 0.1f) {
            printf("FAIL 5b: Pinned particle 0 moved: (%.3f, %.3f, %.3f)\n",
                   sb.positions[0].x, sb.positions[0].y, sb.positions[0].z);
            ++failures;
        }
        if (std::abs(sb.positions[3].y) > 0.1f) {
            printf("FAIL 5c: Pinned particle 3 moved: (%.3f, %.3f, %.3f)\n",
                   sb.positions[3].x, sb.positions[3].y, sb.positions[3].z);
            ++failures;
        }

        // The distance constraints should still be roughly satisfied.
        bool constraintsOk = true;
        for (const auto& dc : sb.distanceConstraints) {
            Vec3f delta = sb.positions[dc.i] - sb.positions[dc.j];
            float dist = delta.length();
            float error = std::abs(dist - dc.restLength) / dc.restLength;
            if (error > 0.5f) {  // Allow up to 50% stretch (cloth is flexible).
                constraintsOk = false;
                break;
            }
        }

        if (!constraintsOk) {
            printf("FAIL 5d: Distance constraints badly violated\n");
            ++failures;
        }

        printf("PASS 5: Cloth gravity simulation\n");
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 6. Soft body collision with a rigid sphere
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;
        PhysicsWorld world;

        // Create a static sphere.
        ShapeHandle sphereShape = world.createShape(Sphere{2.0f});
        RigidBodyDesc sphereDesc;
        sphereDesc.motionType = MotionType::Static;
        sphereDesc.position = Vec3f(0.0f, 0.0f, 0.0f);
        sphereDesc.setShape(sphereShape);
        world.createBody(sphereDesc);

        // Create a small cloth falling onto the sphere.
        auto cloth = SoftBody::createCloth(3, 3, 1.0f, 1.0f);
        // Offset cloth upward so it falls onto the sphere.
        for (auto& pos : cloth.positions) {
            pos.y += 5.0f;
        }
        for (auto& prev : cloth.positionsPrev) {
            prev.y += 5.0f;
        }
        cloth.collisionMargin = 0.01f;
        cloth.constraintIterations = 6;
        world.addSoftBody(std::move(cloth));

        // Simulate for 3 seconds.
        for (int i = 0; i < 180; ++i) {
            world.step(1.0f / 60.0f);
        }

        // All particles should be above or on the sphere surface.
        auto& sb = world.softBodies()[0];
        bool anyPenetrating = false;
        for (std::size_t i = 0; i < sb.particleCount(); ++i) {
            float dist = sb.positions[i].length();
            if (dist < 1.9f) {  // Allow small margin
                anyPenetrating = true;
                break;
            }
        }

        if (anyPenetrating) {
            printf("FAIL 6a: Particles penetrating the sphere.\n");
            for (std::size_t i = 0; i < sb.particleCount(); ++i) {
                printf("  [%zu] pos=(%.3f, %.3f, %.3f) dist=%.3f\n",
                       i, sb.positions[i].x, sb.positions[i].y,
                       sb.positions[i].z, sb.positions[i].length());
            }
            ++failures;
        }

        printf("PASS 6: Cloth-sphere collision\n");
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 7. Soft body collision with a rigid box (ground plane)
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;
        PhysicsWorld world;

        // Create a ground plane.
        ShapeHandle groundShape = world.createShape(Plane{});
        RigidBodyDesc groundDesc;
        groundDesc.motionType = MotionType::Static;
        groundDesc.position = Vec3f(0.0f, -0.5f, 0.0f);
        groundDesc.setShape(groundShape);
        world.createBody(groundDesc);

        // Create a volume body above the ground.
        auto volume = SoftBody::createVolume(Vec3f(0.0f, 5.0f, 0.0f), 1.0f, 1.0f);
        volume.collisionMargin = 0.02f;
        volume.constraintIterations = 8;
        volume.damping = 0.05f;
        SoftBodyHandle hVol = world.addSoftBody(std::move(volume));

        // Simulate for 3 seconds.
        for (int i = 0; i < 180; ++i) {
            world.step(1.0f / 60.0f);
        }

        // Volume should have fallen onto the ground (no particles below plane).
        auto& sb = world.softBodies()[hVol];
        bool belowGround = false;
        for (std::size_t i = 0; i < sb.particleCount(); ++i) {
            // Plane at y = -0.5, plus margin.
            if (sb.positions[i].y < -0.55f) {
                belowGround = true;
                break;
            }
        }

        if (belowGround) {
            printf("FAIL 7a: Volume particles below ground plane.\n");
            for (std::size_t i = 0; i < sb.particleCount(); ++i) {
                printf("  [%zu] pos=(%.3f, %.3f, %.3f)\n",
                       i, sb.positions[i].x, sb.positions[i].y, sb.positions[i].z);
            }
            ++failures;
        }

        // Volume should have settled (low kinetic energy).
        // Positions should not have changed much between last steps.
        bool settled = true;
        (void)settled;

        printf("PASS 7: Volume-plane collision\n");
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // 8. Soft body self-collision — particle-particle repulsion via spatial hash
    // ════════════════════════════════════════════════════════════════════════════════════════════
    {
        ++tests;

        // Create a simple soft body with two clusters of particles that are NOT connected
        // by distance constraints.  Place the clusters overlapping, then verify the spatial-
        // hash accelerated self-collision pushes them apart.
        //
        // Cluster A: 4 particles at (0, 0, 0), (0, 0, 0.1), (0, 0.1, 0), (0, 0.1, 0.1)
        // Cluster B: 4 particles at same positions (overlapping)
        // No distance constraints between clusters — only within each cluster.
        // With self-collision, cluster B should be pushed away from cluster A.

        constexpr std::size_t kClusterSize = 4;
        constexpr std::size_t kNumParticles = kClusterSize * 2;

        SoftBody sb;
        sb.enableSelfCollision = true;
        sb.selfCollisionConfig.stiffness = 0.9f;
        sb.selfCollisionConfig.repulsionRadiusMult = 3.0f;
        sb.collisionMargin = 0.02f;
        sb.constraintIterations = 15;
        sb.gravity = Vec3f::zero();
        sb.damping = 0.0f;  // no damping — let repulsion act freely

        // Cluster A: particles 0-3 at positions centered near origin.
        const float cs = 0.1f;
        Vec3f clusterA[kClusterSize] = {
            Vec3f(0.0f, 0.0f, 0.0f),
            Vec3f(0.0f, 0.0f, cs),
            Vec3f(0.0f, cs, 0.0f),
            Vec3f(0.0f, cs, cs),
        };
        // Cluster B: particles 4-7 at the SAME positions (overlapping).
        Vec3f clusterB[kClusterSize] = {
            Vec3f(0.0f, 0.0f, 0.0f),
            Vec3f(0.0f, 0.0f, cs),
            Vec3f(0.0f, cs, 0.0f),
            Vec3f(0.0f, cs, cs),
        };

        float invMass = 1.0f;
        for (std::size_t i = 0; i < kClusterSize; ++i) {
            // Cluster A.
            sb.positions.push_back(clusterA[i]);
            sb.positionsPrev.push_back(clusterA[i]);
            sb.inverseMasses.push_back(invMass);
            sb.pinned.push_back(0);
        }
        for (std::size_t i = 0; i < kClusterSize; ++i) {
            // Cluster B — same positions (overlapping).
            sb.positions.push_back(clusterB[i]);
            sb.positionsPrev.push_back(clusterB[i]);
            sb.inverseMasses.push_back(invMass);
            sb.pinned.push_back(0);
        }

        // Add distance constraints WITHIN each cluster (to keep each cluster cohesive).
        auto addClusterConstraints = [&](std::uint32_t base) {
            for (std::uint32_t i = 0; i < kClusterSize; ++i) {
                for (std::uint32_t j = i + 1; j < kClusterSize; ++j) {
                    float rest = (sb.positions[base + i] - sb.positions[base + j]).length();
                    if (rest > 0.0f) {
                        sb.distanceConstraints.push_back({base + i, base + j, rest});
                    }
                }
            }
        };
        addClusterConstraints(0);  // cluster A
        addClusterConstraints(4);  // cluster B

        // Run the solver.
        SoftBodySolver solver;
        const std::vector<bool> emptyActive;

        for (int iter = 0; iter < 10; ++iter) {
            solver.step(1.0f / 60.0f, sb,
                        0, nullptr, nullptr,
                        nullptr, nullptr,
                        nullptr, nullptr, nullptr,
                        nullptr, emptyActive);
        }

        // After 10 iterations, the two clusters should have separated.
        // Compute the centroid of each cluster.
        Vec3f centroidA(0.0f), centroidB(0.0f);
        for (std::size_t i = 0; i < kClusterSize; ++i) {
            centroidA += sb.positions[i];
            centroidB += sb.positions[kClusterSize + i];
        }
        centroidA *= (1.0f / static_cast<float>(kClusterSize));
        centroidB *= (1.0f / static_cast<float>(kClusterSize));

        float separation = (centroidB - centroidA).length();

        // The separation should be at least the repulsion radius.
        float expectedMinSep = sb.collisionMargin * sb.selfCollisionConfig.repulsionRadiusMult;
        bool separated = (separation >= expectedMinSep * 0.8f);

        // Also check no particle from one cluster is overlapping the other cluster.
        bool anyPenetrating = false;
        for (std::size_t i = 0; i < kClusterSize; ++i) {
            for (std::size_t j = kClusterSize; j < kNumParticles; ++j) {
                float dist = (sb.positions[i] - sb.positions[j]).length();
                if (dist < sb.collisionMargin * 0.5f) {
                    anyPenetrating = true;
                    break;
                }
            }
        }

        if (!separated || anyPenetrating) {
            printf("FAIL 8: Self-collision repulsion insufficient.\n");
            printf("       separation=%.4f (expected >= %.4f)\n",
                   separation, expectedMinSep * 0.8f);
            printf("       anyPenetrating=%d\n", anyPenetrating);
            printf("       Cluster A centroids: (%.4f, %.4f, %.4f)\n",
                   centroidA.x, centroidA.y, centroidA.z);
            printf("       Cluster B centroids: (%.4f, %.4f, %.4f)\n",
                   centroidB.x, centroidB.y, centroidB.z);
            printf("       Positions:\n");
            for (std::size_t i = 0; i < kNumParticles; ++i) {
                printf("       [%zu] (%.4f, %.4f, %.4f)%s\n",
                       i, sb.positions[i].x, sb.positions[i].y, sb.positions[i].z,
                       i < kClusterSize ? " A" : " B");
            }
            ++failures;
        } else {
            printf("PASS 8: Self-collision repulsion — clusters separated (sep=%.4f)\n",
                   separation);
        }
    }

    // ════════════════════════════════════════════════════════════════════════════════════════════
    // Results
    // ════════════════════════════════════════════════════════════════════════════════════════════
    printf("\n═══════════════════════════════════════════════════════════════════════════════\n");
    printf("  SoftBody: %d tests, %d failures\n", tests, failures);
    printf("═══════════════════════════════════════════════════════════════════════════════\n");

    return failures > 0 ? 1 : 0;
}
