# CMake generated Testfile for 
# Source directory: E:/CiPhyxs
# Build directory: E:/CiPhyxs/build2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_alignment "E:/CiPhyxs/build2/test_alignment.exe")
set_tests_properties(test_alignment PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_collision "E:/CiPhyxs/build2/test_collision.exe")
set_tests_properties(test_collision PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_final "E:/CiPhyxs/build2/test_final.exe")
set_tests_properties(test_final PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_joints "E:/CiPhyxs/build2/test_joints.exe")
set_tests_properties(test_joints PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_new_features "E:/CiPhyxs/build2/test_new_features.exe")
set_tests_properties(test_new_features PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_parallel "E:/CiPhyxs/build2/test_parallel.exe")
set_tests_properties(test_parallel PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_sap "E:/CiPhyxs/build2/test_sap.exe")
set_tests_properties(test_sap PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_convexmesh "E:/CiPhyxs/build2/test_convexmesh.exe")
set_tests_properties(test_convexmesh PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_trimesh "E:/CiPhyxs/build2/test_trimesh.exe")
set_tests_properties(test_trimesh PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_ccd "E:/CiPhyxs/build2/test_ccd.exe")
set_tests_properties(test_ccd PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_ragdoll "E:/CiPhyxs/build2/test_ragdoll.exe")
set_tests_properties(test_ragdoll PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_dbvt "E:/CiPhyxs/build2/test_dbvt.exe")
set_tests_properties(test_dbvt PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_contactreduction "E:/CiPhyxs/build2/test_contactreduction.exe")
set_tests_properties(test_contactreduction PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_vehicle "E:/CiPhyxs/build2/test_vehicle.exe")
set_tests_properties(test_vehicle PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_character "E:/CiPhyxs/build2/test_character.exe")
set_tests_properties(test_character PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_taskgraph "E:/CiPhyxs/build2/test_taskgraph.exe")
set_tests_properties(test_taskgraph PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_softbody "E:/CiPhyxs/build2/test_softbody.exe")
set_tests_properties(test_softbody PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_fracture "E:/CiPhyxs/build2/test_fracture.exe")
set_tests_properties(test_fracture PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(DeepStackTest "E:/CiPhyxs/build2/DeepStackTest.exe")
set_tests_properties(DeepStackTest PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(TunnelingTest "E:/CiPhyxs/build2/TunnelingTest.exe")
set_tests_properties(TunnelingTest PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(CCDConvexMeshTest "E:/CiPhyxs/build2/CCDConvexMeshTest.exe")
set_tests_properties(CCDConvexMeshTest PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(ChaosDensityTest "E:/CiPhyxs/build2/ChaosDensityTest.exe")
set_tests_properties(ChaosDensityTest PROPERTIES  TIMEOUT "360" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(DeterminismTest "E:/CiPhyxs/build2/DeterminismTest.exe")
set_tests_properties(DeterminismTest PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(MultibodyCrashTest "E:/CiPhyxs/build2/MultibodyCrashTest.exe")
set_tests_properties(MultibodyCrashTest PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(ExtremeCcdTest "E:/CiPhyxs/build2/ExtremeCcdTest.exe")
set_tests_properties(ExtremeCcdTest PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(LowEndBenchmark "E:/CiPhyxs/build2/LowEndBenchmark.exe")
set_tests_properties(LowEndBenchmark PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;134;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
