# CMake generated Testfile for 
# Source directory: E:/CiPhyxs
# Build directory: E:/CiPhyxs/build2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_alignment "E:/CiPhyxs/build2/test_alignment.exe")
set_tests_properties(test_alignment PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_collision "E:/CiPhyxs/build2/test_collision.exe")
set_tests_properties(test_collision PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_final "E:/CiPhyxs/build2/test_final.exe")
set_tests_properties(test_final PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_joints "E:/CiPhyxs/build2/test_joints.exe")
set_tests_properties(test_joints PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_new_features "E:/CiPhyxs/build2/test_new_features.exe")
set_tests_properties(test_new_features PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_parallel "E:/CiPhyxs/build2/test_parallel.exe")
set_tests_properties(test_parallel PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_sap "E:/CiPhyxs/build2/test_sap.exe")
set_tests_properties(test_sap PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_convexmesh "E:/CiPhyxs/build2/test_convexmesh.exe")
set_tests_properties(test_convexmesh PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_trimesh "E:/CiPhyxs/build2/test_trimesh.exe")
set_tests_properties(test_trimesh PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_ccd "E:/CiPhyxs/build2/test_ccd.exe")
set_tests_properties(test_ccd PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_ragdoll "E:/CiPhyxs/build2/test_ragdoll.exe")
set_tests_properties(test_ragdoll PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_dbvt "E:/CiPhyxs/build2/test_dbvt.exe")
set_tests_properties(test_dbvt PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_contactreduction "E:/CiPhyxs/build2/test_contactreduction.exe")
set_tests_properties(test_contactreduction PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_vehicle "E:/CiPhyxs/build2/test_vehicle.exe")
set_tests_properties(test_vehicle PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_character "E:/CiPhyxs/build2/test_character.exe")
set_tests_properties(test_character PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_taskgraph "E:/CiPhyxs/build2/test_taskgraph.exe")
set_tests_properties(test_taskgraph PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_softbody "E:/CiPhyxs/build2/test_softbody.exe")
set_tests_properties(test_softbody PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(test_fracture "E:/CiPhyxs/build2/test_fracture.exe")
set_tests_properties(test_fracture PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;99;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(DeepStackTest "E:/CiPhyxs/build2/DeepStackTest.exe")
set_tests_properties(DeepStackTest PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;132;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(TunnelingTest "E:/CiPhyxs/build2/TunnelingTest.exe")
set_tests_properties(TunnelingTest PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;132;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(CCDConvexMeshTest "E:/CiPhyxs/build2/CCDConvexMeshTest.exe")
set_tests_properties(CCDConvexMeshTest PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;132;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(ChaosDensityTest "E:/CiPhyxs/build2/ChaosDensityTest.exe")
set_tests_properties(ChaosDensityTest PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;132;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(DeterminismTest "E:/CiPhyxs/build2/DeterminismTest.exe")
set_tests_properties(DeterminismTest PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;132;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(MultibodyCrashTest "E:/CiPhyxs/build2/MultibodyCrashTest.exe")
set_tests_properties(MultibodyCrashTest PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;132;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
add_test(ExtremeCcdTest "E:/CiPhyxs/build2/ExtremeCcdTest.exe")
set_tests_properties(ExtremeCcdTest PROPERTIES  _BACKTRACE_TRIPLES "E:/CiPhyxs/CMakeLists.txt;132;add_test;E:/CiPhyxs/CMakeLists.txt;0;")
